### ISSUE TITLE
[Suggestion] Do you know if its possible to also display the user's badge ?

### ISSUE THREAD

**Issue by Decryptu** [Lillinator/topic-list-author#1]
Hello ! Do you know if its possible to also display the user badge/flair on the profil picture in the topic list ? 

<img width="79" alt="Capture d’écran 2023-10-18 à 13 41 48" src="https://github.com/Lillinator/topic-list-author/assets/90518536/e024b935-7803-460f-b839-24b7543e71b5">

I tried to do it myself, but it wasn't successful.

**Comment by Lillinator** [comment]
no that can't be done with this component.
